import { SIM_LABEL } from "@/agent/prompts";
import type { Quote } from "./schemas";
import type { Report } from "./types";

const methodName = (m: Report["scope"]["method"]) => (m === "usability_test" ? "Usability test (simulated)" : "Focus group (simulated)");

function personaName(r: Report, id: string) {
  const p = r.scope.personas.find((x) => x.id === id);
  return p ? `${p.name} (${p.label})` : id;
}

function quotes(r: Report, qs: Quote[]): string {
  return qs
    .map((q) => {
      const unverified = (q as { verified?: boolean }).verified === false ? " ⚠ not matched to transcript" : "";
      return `> "${q.text}" — ${personaName(r, q.personaId)}, simulated persona, line ${q.lineId}${unverified}`;
    })
    .join("\n");
}

/** Markdown export. Every export carries the simulated-research label. */
export function reportToMarkdown(r: Report, meta: { version: number; approvedAt: string | null }): string {
  const d = r.draft;
  const out: string[] = [];
  out.push(`# ${r.title}`);
  out.push(`**${SIM_LABEL}.** Every participant, quote and observation below was generated by AI personas, not real users.`);
  out.push(
    `Report v${meta.version}${meta.approvedAt ? ` · approved by the PM ${meta.approvedAt.slice(0, 10)}` : " · DRAFT (not approved)"} · generated ${r.generatedAt.slice(0, 10)}`,
  );
  out.push(`## Study scope`);
  out.push(
    [
      `- **Feature:** ${r.scope.featureUnderTest}`,
      `- **Decision this informs (owned by the PM):** ${r.scope.decisionToSupport}`,
      `- **Method:** ${methodName(r.scope.method)}`,
      `- **Simulated participants (${r.scope.participantCount}):** ${r.scope.personas.map((p) => `${p.name} — ${p.label}`).join("; ")}`,
      `- **Screens:** ${r.scope.screens.map((s) => `${s.code} ${s.label}`).join(", ") || "none"}`,
      `- **Approved inputs:** study design v${r.scope.designVersion}, personas v${r.scope.personaVersion}`,
    ].join("\n"),
  );
  out.push(`## Executive summary\n${d.executiveSummary}`);
  out.push(`## Research questions`);
  for (const rq of r.researchQuestions) {
    const a = d.researchQuestionAnswers.find((x) => x.questionId === rq.id);
    out.push(`### ${rq.id}. ${rq.text}\n${a ? `${a.answer}\n\n*Confidence: ${a.confidence}*\n\n${quotes(r, a.evidence)}` : "_Not answered._"}`);
  }
  if (r.taskMetrics.length) {
    out.push(`## Task results (simulated)`);
    out.push(
      [
        "| Task | Completed | With difficulty | Failed | Gave up | Avg. ease (1–7) |",
        "|---|---|---|---|---|---|",
        ...r.taskMetrics.map(
          (t) => `| ${t.taskId} ${t.title} | ${t.completed} | ${t.completedWithDifficulty} | ${t.failed} | ${t.gaveUp} | ${t.averageEase ?? "–"} |`,
        ),
      ].join("\n"),
    );
  }
  out.push(`## Findings`);
  for (const f of d.findings) {
    out.push(
      `### ${f.id}. ${f.title} — ${f.severity}\n**Observation:** ${f.observation}\n\n**Interpretation:** ${f.interpretation}\n\n*Personas:* ${f.personaIds.map((id) => personaName(r, id)).join(", ")} · *Research questions:* ${f.relatedQuestionIds.join(", ")}\n\n${quotes(r, f.evidence)}`,
    );
  }
  if (d.patterns.length) out.push(`## Patterns\n${d.patterns.map((p) => `- **${p.title}:** ${p.description}`).join("\n")}`);
  if (d.contradictions.length)
    out.push(`## Contradictions\n${d.contradictions.map((c) => `- **${c.title}:** ${c.description}\n${quotes(r, c.evidence)}`).join("\n")}`);
  out.push(`## Recommendations`);
  out.push(d.recommendations.map((x) => `- **${x.id}. ${x.title}** (${x.priority} priority · ${x.type.replace(/_/g, " ")} · addresses ${x.findingIds.join(", ")}): ${x.detail}`).join("\n"));
  if (d.personaHighlights.length) out.push(`## Persona highlights\n${d.personaHighlights.map((p) => `- **${personaName(r, p.personaId)}:** ${p.summary}`).join("\n")}`);
  out.push(`## Limitations\n${d.limitations.map((l) => `- ${l}`).join("\n")}`);
  out.push(`## What to validate with real users\n${d.realUserValidation}`);
  if (r.pmNotes.trim()) out.push(`## PM notes\n${r.pmNotes}`);
  out.push(
    `---\n*${SIM_LABEL}. This report summarises a simulated study and does not make the ${r.scope.decisionToSupport} decision. That decision rests with the product manager and team. Quote check: ${r.quoteCheck.verified} of ${r.quoteCheck.total} quotes matched to the simulated transcript.*`,
  );
  return out.join("\n\n") + "\n";
}
