import type { Quote } from "@/lib/schemas";
import type { Report } from "@/lib/types";

/** Read-only rendering of a report. Hook-free so the share page can render it on the server. */

const SEVERITY: Record<string, string> = {
  critical: "bg-rose-100 text-rose-800",
  major: "bg-orange-100 text-orange-800",
  minor: "bg-slate-100 text-slate-700",
  positive: "bg-emerald-100 text-emerald-800",
};

export function ReportDocument({
  report,
  version,
  approvedAt,
  transcriptHref,
}: {
  report: Report;
  version: number;
  approvedAt: string | null;
  transcriptHref?: string;
}) {
  const d = report.draft;
  const name = (id: string) => report.scope.personas.find((p) => p.id === id)?.name ?? id;

  const Quotes = ({ items }: { items: Quote[] }) =>
    items.length ? (
      <div className="mt-2 space-y-1.5">
        {items.map((q, i) => {
          const unverified = (q as { verified?: boolean }).verified === false;
          return (
            <blockquote key={i} className="border-l-2 border-amber-300 bg-amber-50/50 py-1 pl-3 text-sm text-slate-700">
              “{q.text}”
              <span className="ml-1 text-xs text-slate-500">
                — {name(q.personaId)} (AI persona),{" "}
                {transcriptHref ? (
                  <a href={`${transcriptHref}#${q.lineId}`} className="underline decoration-dotted">
                    {q.lineId}
                  </a>
                ) : (
                  q.lineId
                )}
              </span>
              {unverified && <span className="ml-1 text-xs font-medium text-rose-600">⚠ not found in transcript</span>}
            </blockquote>
          );
        })}
      </div>
    ) : null;

  return (
    <article className="print-full space-y-8 rounded-xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8">
      <header className="space-y-3 border-b border-slate-100 pb-6">
        <div className="flex items-start gap-2 rounded-lg border border-amber-200 bg-amber-50 px-3 py-2 text-sm text-amber-900">
          <span aria-hidden>◆</span>
          <span>
            <strong>AI-generated simulated research.</strong> Every participant, quote and observation here was generated by AI personas, not real
            users. It does not replace real-user validation.
          </span>
        </div>
        <h1 className="text-2xl font-semibold tracking-tight">{report.title}</h1>
        <p className="text-sm text-slate-500">
          Report v{version} · {approvedAt ? `approved ${new Date(approvedAt).toLocaleDateString()}` : "draft, not yet approved"} · generated{" "}
          {new Date(report.generatedAt).toLocaleDateString()}
        </p>
        <dl className="grid gap-x-6 gap-y-1 text-sm sm:grid-cols-2">
          <div>
            <dt className="inline text-slate-500">Feature: </dt>
            <dd className="inline">{report.scope.featureUnderTest}</dd>
          </div>
          <div>
            <dt className="inline text-slate-500">Decision (owned by the PM): </dt>
            <dd className="inline capitalize">{report.scope.decisionToSupport}</dd>
          </div>
          <div>
            <dt className="inline text-slate-500">Method: </dt>
            <dd className="inline">{report.scope.method === "usability_test" ? "Simulated usability test" : "Simulated focus group"}</dd>
          </div>
          <div>
            <dt className="inline text-slate-500">Participants: </dt>
            <dd className="inline">{report.scope.personas.map((p) => `${p.name} (${p.label})`).join(", ")}</dd>
          </div>
          <div>
            <dt className="inline text-slate-500">Screens: </dt>
            <dd className="inline">{report.scope.screens.map((s) => `${s.code} ${s.label}`).join(", ") || "none"}</dd>
          </div>
          <div>
            <dt className="inline text-slate-500">Approved inputs: </dt>
            <dd className="inline">
              design v{report.scope.designVersion}, personas v{report.scope.personaVersion}
            </dd>
          </div>
        </dl>
      </header>

      <section>
        <h2 className="text-lg font-semibold">Executive summary</h2>
        <p className="mt-2 whitespace-pre-wrap leading-relaxed text-slate-700">{d.executiveSummary}</p>
      </section>

      <section>
        <h2 className="text-lg font-semibold">Research questions</h2>
        <div className="mt-3 space-y-5">
          {report.researchQuestions.map((rq) => {
            const a = d.researchQuestionAnswers.find((x) => x.questionId === rq.id);
            return (
              <div key={rq.id}>
                <p className="font-medium">
                  <span className="font-mono text-xs text-slate-400">{rq.id}</span> {rq.text}
                </p>
                {a ? (
                  <>
                    <p className="mt-1 whitespace-pre-wrap text-sm leading-relaxed text-slate-700">{a.answer}</p>
                    <p className="mt-1 text-xs text-slate-500">Confidence: {a.confidence}</p>
                    <Quotes items={a.evidence} />
                  </>
                ) : (
                  <p className="mt-1 text-sm text-slate-400">Not answered.</p>
                )}
              </div>
            );
          })}
        </div>
      </section>

      {report.taskMetrics.length > 0 && (
        <section>
          <h2 className="text-lg font-semibold">Task results (simulated)</h2>
          <div className="mt-3 overflow-x-auto">
            <table className="w-full text-left text-sm">
              <thead className="text-xs uppercase text-slate-500">
                <tr className="border-b border-slate-200">
                  <th className="py-2 pr-3">Task</th>
                  <th className="px-2">Completed</th>
                  <th className="px-2">With difficulty</th>
                  <th className="px-2">Failed</th>
                  <th className="px-2">Gave up</th>
                  <th className="px-2">Avg. ease (1–7)</th>
                </tr>
              </thead>
              <tbody>
                {report.taskMetrics.map((t) => (
                  <tr key={t.taskId} className="border-b border-slate-100">
                    <td className="py-2 pr-3">
                      <span className="font-mono text-xs text-slate-400">{t.taskId}</span> {t.title}
                    </td>
                    <td className="px-2">{t.completed}</td>
                    <td className="px-2">{t.completedWithDifficulty}</td>
                    <td className="px-2">{t.failed}</td>
                    <td className="px-2">{t.gaveUp}</td>
                    <td className="px-2">{t.averageEase ?? "–"}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          <p className="mt-2 text-xs text-slate-500">Small simulated samples show what problems exist and why, not how often real users would hit them.</p>
        </section>
      )}

      <section>
        <h2 className="text-lg font-semibold">Findings</h2>
        <div className="mt-3 space-y-5">
          {d.findings.map((f) => (
            <div key={f.id} className="rounded-lg border border-slate-200 p-4">
              <div className="flex flex-wrap items-center gap-2">
                <span className="font-mono text-xs text-slate-400">{f.id}</span>
                <span className="font-medium">{f.title}</span>
                <span className={`rounded-full px-2 py-0.5 text-xs font-medium ${SEVERITY[f.severity]}`}>{f.severity}</span>
                <span className="text-xs text-slate-500">
                  {f.personaIds.length} of {report.scope.participantCount} personas · {f.relatedQuestionIds.join(", ")}
                </span>
              </div>
              <p className="mt-2 text-sm">
                <span className="font-medium text-slate-600">Observation: </span>
                {f.observation}
              </p>
              <p className="mt-1 text-sm">
                <span className="font-medium text-slate-600">Interpretation: </span>
                {f.interpretation}
              </p>
              <Quotes items={f.evidence} />
            </div>
          ))}
        </div>
      </section>

      {d.patterns.length > 0 && (
        <section>
          <h2 className="text-lg font-semibold">Patterns</h2>
          <ul className="mt-2 space-y-2 text-sm">
            {d.patterns.map((p, i) => (
              <li key={i}>
                <span className="font-medium">{p.title}:</span> {p.description} <span className="text-xs text-slate-500">({p.personaIds.map(name).join(", ")})</span>
              </li>
            ))}
          </ul>
        </section>
      )}

      {d.contradictions.length > 0 && (
        <section>
          <h2 className="text-lg font-semibold">Contradictions</h2>
          <div className="mt-2 space-y-3 text-sm">
            {d.contradictions.map((c, i) => (
              <div key={i}>
                <p>
                  <span className="font-medium">{c.title}:</span> {c.description}
                </p>
                <Quotes items={c.evidence} />
              </div>
            ))}
          </div>
        </section>
      )}

      <section>
        <h2 className="text-lg font-semibold">Recommendations</h2>
        <ol className="mt-3 space-y-3">
          {d.recommendations.map((r) => (
            <li key={r.id} className="text-sm">
              <div className="flex flex-wrap items-center gap-2">
                <span className="font-mono text-xs text-slate-400">{r.id}</span>
                <span className="font-medium">{r.title}</span>
                <span className="rounded-full bg-indigo-50 px-2 py-0.5 text-xs text-indigo-700">{r.priority} priority</span>
                <span className="text-xs text-slate-500">
                  {r.type.replace(/_/g, " ")} · addresses {r.findingIds.join(", ")}
                </span>
              </div>
              <p className="mt-1 text-slate-700">{r.detail}</p>
            </li>
          ))}
        </ol>
      </section>

      {d.personaHighlights.length > 0 && (
        <section>
          <h2 className="text-lg font-semibold">Persona highlights</h2>
          <ul className="mt-2 space-y-1.5 text-sm">
            {d.personaHighlights.map((p) => (
              <li key={p.personaId}>
                <span className="font-medium">{name(p.personaId)}:</span> {p.summary}
              </li>
            ))}
          </ul>
        </section>
      )}

      <section>
        <h2 className="text-lg font-semibold">Limitations</h2>
        <ul className="mt-2 list-disc space-y-1 pl-5 text-sm text-slate-700">
          {d.limitations.map((l, i) => (
            <li key={i}>{l}</li>
          ))}
        </ul>
        <h3 className="mt-4 font-medium">What to validate with real users</h3>
        <p className="mt-1 text-sm text-slate-700">{d.realUserValidation}</p>
      </section>

      {report.pmNotes.trim() && (
        <section>
          <h2 className="text-lg font-semibold">PM notes</h2>
          <p className="mt-2 whitespace-pre-wrap text-sm text-slate-700">{report.pmNotes}</p>
        </section>
      )}

      <footer className="border-t border-slate-100 pt-4 text-xs text-slate-500">
        AI-generated simulated research. This report does not make the {report.scope.decisionToSupport} decision; that rests with the product manager
        and team. Quote check: {report.quoteCheck.verified} of {report.quoteCheck.total} quotes matched to the simulated transcript.
      </footer>
    </article>
  );
}
